### PR TITLE
Update French translations

### PR DESCRIPTION
**Pull request by NathanBnm**

### CODE REVIEW

**Review by jeremypw — APPROVED** [review]
Thanks!

**Comment by jeremypw** [comment]
@NathanBnm : Is the following translation correct? I am not French but it seems to mean the opposite:

```
msgid "Alternative solution found"
msgstr "Pas de solution avancée trouvée"
```

**Comment by jeremypw** [comment]
@NathanBnm :  I also have the following questions on the translations, generally caused by the ambiguous abbreviated nature of the English used and the lack of translator comments provided.

I will push a PR with appropriate translator comments asap to help other translators.

```
msgid "Correct solution"
msgstr "Corriger la solution"
```
Here "correct" should be an adjective, not a verb.

```
msgid "Solution found. %s"
msgstr "Solution simple trouvée. %s"
```
Here, the %s is a placeholder for the difficulty of the puzzle (Easy, Difficult etc) so you should not use the word "simple" in the translation.

```
msgid "No solution found"
msgstr "Pas de solution simple trouvée"
```
This message indicates that no solution of any kind has been found so the word "simple" should not be in the translation.

```
msgid "Generate %s puzzle"
msgstr "Générer %s puzzle"
```
Here `%s` is a placeholder for an adjective describing the difficulty of the puzzle, should it not follow 'puzzle' in the translation?

These were picked when I uploaded the translations to Zanata and it marked some as 'fuzzy'

**Comment by NathanBnm** [comment]
> @NathanBnm : Is the following translation correct? I am not French but it seems to mean the opposite:
> 
> ```
> msgid "Alternative solution found"
> msgstr "Pas de solution avancée trouvée"
> ```

That's not correct at all, I think that some translations have been mixed up when you added new ones.
That should be "Solution alternative trouvée"

I'm going to check the file. Thanks for context help

**Comment by NathanBnm** [comment]
> @NathanBnm : I also have the following questions on the translations, generally caused by the ambiguous abbreviated nature of the English used and the lack of translator comments provided.
> 
> I will push a PR with appropriate translator comments asap to help other translators.
> 
> ```
> msgid "Correct solution"
> msgstr "Corriger la solution"
> ```
> Here "correct" should be an adjective, not a verb.
> 
I have made the changes for this, It's hard to guess without context the two solutions can be possible in French.
> ```
> msgid "Solution found. %s"
> msgstr "Solution simple trouvée. %s"
> ```
> Here, the %s is a placeholder for the difficulty of the puzzle (Easy, Difficult etc) so you should not use the word "simple" in the translation.
> 
I think that I didn't see that the string was changed.
> ```
> msgid "No solution found"
> msgstr "Pas de solution simple trouvée"
> ```
> This message indicates that no solution of any kind has been found so the word "simple" should not be in the translation.
> 
Same here.
> ```
> msgid "Generate %s puzzle"
> msgstr "Générer %s puzzle"
> ```
> Here `%s` is a placeholder for an adjective describing the difficulty of the puzzle, should it not follow 'puzzle' in the translation?
> 
I thought that it was a number of puzzle ^^' But now changes are effective.
> These were picked when I uploaded the translations to Zanata and it marked some as 'fuzzy'

**Comment by NathanBnm** [comment]
So I opened #29

**Pull request merged**
