### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by NathanBnm**
Hi! I made some changes to your app because there were some issues, especially about translations. Here is the changelog:

# Changelog
- [X] Fix some typos
- [X] Remove incorrect language files
- [X] Update language files
- [X] Fix appdata (with `.in` extension) -> Correct formatting
- [X] Update French translations

I also changed the `- npm install @elementaryos/houston` line to `- npm i -g @elementaryos/houston` for Travis CI, this should be better and fix some possible build issues.

Feel free to ask if you have any questions :smile:

**This PR is ready for review**

### CODE REVIEW

**Comment by NathanBnm** [comment]
Apparently there is a problem with `appdata.xml` file validation, I tried different ways but I'm not able to fix the issue. Can you help?

**Comment by jeremypw** [comment]
Thanks for the contribution!

I am not sure adding a very large number of untranslated language files is a good idea.  There is discussion in the elementary team about reducing the number of "core" languages included by default.  The chances of this application attracting a large number of translators is, to say the least, remote.

I think I might follow e.g. https://github.com/Philip-Scott/Notes-up/tree/master/po and just add translations as they are requested/offered.

Would you mind not adding the extra untranslated language files for now while I decide what to do about translations?

I'll look into the appdata problem.

**Comment by NathanBnm** [comment]
I understand your point, I'm going to remove empty translation files :wink:

**Comment by NathanBnm** [comment]
Done :smile: I made the post_install.py script executable too, this may solves some compilation issues with Travis CI.

**Comment by jeremypw** [comment]
Thanks!  I imported some of your changes to master and fixed the appdata problem.   Coud you fix the conflicts taking the master version of the conflicting code?

**Comment by NathanBnm** [comment]
Sure, I'll do that :+1:

**Comment by NathanBnm** [comment]
Should be fixed now :smile:

**Comment by jeremypw** [comment]
Hurrah - passes Travis CI now!

**Pull request merged**
